name: Update Hydra Key
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Explicitly giving write access
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4 # Updated to v4 for Node 24 support

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Python Script
        run: python generate_key.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "HydraBot"
          git config --global user.email "bot@hydra.com"
          git add key.txt
          git commit -m "Updated Key" || echo "No changes to commit"
          git push
